services:
  zuploader:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - /srv/zuploader:/srv/zuploader
      - ./config.toml:/app/config.toml:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "7"
